// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package gennyDemo

import "github.com/cstockton/go-conv"

// 首先 我们实现了一个任意类型
func SayString(input int) string {
	res, _ := conv.String(input)
	return res
}
